CREATE TABLE IF NOT EXISTS created_assessments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unique_id VARCHAR(36) NOT NULL UNIQUE,
    access_code VARCHAR(6) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    year VARCHAR(4) NOT NULL,
    course VARCHAR(100) NOT NULL,
    sections VARCHAR(50) NOT NULL,
    course_code VARCHAR(20) NOT NULL,
    timer INT NOT NULL COMMENT 'Duration in minutes',
    status ENUM('active', 'closed') NOT NULL DEFAULT 'active',
    school_year VARCHAR(9) NOT NULL COMMENT 'Format: 2024-2025',
    schedule DATETIME NOT NULL COMMENT 'When the assessment will start',
    closing_time DATETIME NOT NULL COMMENT 'When the assessment will automatically close',
    shuffle_mcq BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether to shuffle multiple choice questions',
    shuffle_identification BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether to shuffle identification questions',
    shuffle_true_false BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether to shuffle true/false questions',
    ai_check_identification BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'Whether to use AI for checking identification answers',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id VARCHAR(36) NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES accounts(unique_id) ON DELETE CASCADE,
    INDEX idx_access_code (access_code),
    INDEX idx_status (status),
    INDEX idx_schedule (schedule),
    INDEX idx_owner (owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 